### ISSUE TITLE
Ability to provide DDB client

### ISSUE THREAD

**Issue by jskrt** [cmwhited/apollo-datasource-dynamodb#9]
Can we extend the constructor to allow clients to provide the DDB client? This can serve as an optimization if used with dependency injection.

**Comment by cmwhited** [comment]
Sorry for the late response. Yeah I like that idea. Let me look into it!

**Comment by cmwhited** [comment]
@jskrt checkout PR #16 and let me know if that will solve the problem. I considered making the last param a union type of `ClientConfiguration` or `DynamoDB.DocumentClient` but felt this was cleaner and more backwards compatible.

**Comment by jskrt** [comment]
Sorry, I didn't see this soon enough. Left a comment on there (more of a nit). LGTM otherwise. Thanks for doing this!
